name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  test:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
      - uses: actions/checkout@v4
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Run Tests
        run: |
          set -eo pipefail
          xcodebuild test \
            -scheme IonicPortals \
            -destination 'platform=iOS Simulator,name=iPhone 15' | xcpretty
  validate-podspec:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
      - uses: actions/checkout@v4
      - name: Install cocoapods
        run: gem install cocoapods
      - name: Lint Podspec
        run: pod lib lint
