name: CI

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Show Xcode version
        run: xcodebuild -version
      - uses: actions/checkout@v5
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Run Tests
        run: |
          set -eo pipefail
          xcodebuild test \
            -scheme IonicPortals \
            -destination 'platform=iOS Simulator,name=iPhone 17' | xcpretty
  validate-podspec:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Show Xcode version
        run: xcodebuild -version
      - uses: actions/checkout@v5
      - name: Install cocoapods
        run: gem install cocoapods
      - name: Lint Podspec
        run: pod lib lint
