name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
# on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ce177499ccf9fd2aded3b0426c97e5434c2e8a73
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Latest
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with: 
          path: core/
  verify-ios:
    runs-on: macos-11
    timeout-minutes: 30
    needs:
      - setup
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.2.app
      - uses: actions/checkout@v2
      - name: Install Cocoapods
        run: gem install cocoapods
      - run: pod install
      - run: carthage bootstrap --use-xcframeworks
      - run: npm run verify
  publish-ios:
    runs-on: macos-11
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'Release') && (!contains(github.event.head_commit.message, 'rc') && !contains(github.event.head_commit.message, 'beta') && !contains(github.event.head_commit.message, 'alpha'))
    timeout-minutes: 30
    needs:
        - setup
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_13.2.app
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
        # with:
        #   ref: some-test-branch
      - name: Install Cocoapods
        run: gem install cocoapods
      - name: Deploy to Cocoapods        
        run: |
          set -eo pipefail
          pod trunk push IonicPortals.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
