name: Publish Docs Preview

on: pull_request

permissions:
  contents: read
  deployments: write
  id-token: write

env:
  SLUG: portals-ios-api-ref-${{ github.event.number }}-${{ github.run_id }}

jobs:
  publish-preview-docs:
    runs-on: macos-12
    timeout-minutes: 30
    environment:
      name: preview-${{ github.event.number }}
      url: https://${{ env.SLUG }}.ionicpreview.com
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: sudo xcode-select --switch /Applications/Xcode_14.1.app
      - uses: actions/checkout@v2
      - name: Build Docs
        run: xcodebuild docbuild -scheme IonicPortals -derivedDataPath DerivedData -destination 'platform=iOS Simulator,name=iPhone 14'
      - name: Transform Docs
        run: $(xcrun --find docc) process-archive transform-for-static-hosting DerivedData/Build/Products/Debug-iphonesimulator/IonicPortals.doccarchive --hosting-base-path docs/portals-ios-api-ref --output-path docs
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::319312831725:role/github-docs
          aws-region: us-east-1
      - name: Deploy
        run: |
          aws s3 sync docs s3://ionic-docs/preview/${{ env.SLUG }}/ --exclude '*.html' --cache-control max-age=31536000 --only-show-errors
          aws s3 sync docs s3://ionic-docs/preview/${{ env.SLUG }}/ --exclude '*' --include '*.html' --cache-control max-age=60 --only-show-errors
