name: Publish to Cocoapods

on:
  push:
    tags:
      - "*"

jobs:
  publish-to-cocoapods:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: gem install cocoapods
      - name: Validate podspec
        run: pod spec lint
      - name: Publish podspec
        run: pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
